---

#- name: Initialize an empty list for our strings
#  set_fact:
#    my_strings: []

- name: Setup a string variable
  set_fact:
    my_name: "Max"

- name: Append string to list
  set_fact:
    my_strings: "{{ my_strings }} + [ '{{ my_name }}' ]"

- debug: var=my_strings

- name: Append another item to the list
  set_fact:
    my_strings: "{{ my_strings }} + [ 'Power' ]"
    
- debug: var=my_strings

- name: Append moar items to the list from loop
  set_fact:
    my_strings: "{{ my_strings + [item] }}"
  with_items:
    - Just
    - Don't
    - Have
    - The
    - Power

- debug: var=my_strings

